export const competitionAllList = [
    {
        id: 0,
        image: "/images/competition/list01.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 1,
        image: "/images/competition/list02.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 2,
        image: "/images/competition/list02.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 3,
        image: "/images/competition/list01.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 4,
        image: "/images/competition/list02.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 5,
        image: "/images/competition/list01.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
];

export const competitionExpectedList = [
    {
        id: 0,
        image: "/images/competition/list02.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 1,
        image: "/images/competition/list01.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 2,
        image: "/images/competition/list02.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 3,
        image: "/images/competition/list01.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 4,
        image: "/images/competition/list02.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
    {
        id: 5,
        image: "/images/competition/list01.png",
        category: "지역 대회",
        region: "경기-평택시",
        title: "제3회 딱플 전국 배드민턴 대회",
        schedule: "일정: 2025년 5월 31일 ~ 6월 1일",
    },
];

export const listDatas = [
    {
        id: 0,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제2회 딱플 배드민턴대회",
        competitionYear: "2025",
        teamName: "딱플",
        round: "8강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
        description: "123456566",
        matchResults: [
            {
                location: "충주배드민턴전용체육관",
                date: "2월 8일",
                time: "13:00",
                courtNum: "6",
                num: "17",
                group1User1: "안성만",
                group1User2: "홍수미",
                group1User1TeamName: "일출클럽",
                group1User2TeamName: "일출클럽",
                group1Score: "13",
                group2Score: "25",
                group2Level: "F-K",
                group2User1: "서형민",
                group2User2: "김남옥",
                round: "결승",
            },
            {
                location: "충주배드민턴전용체육관",
                date: "2월 8일",
                time: "13:00",
                courtNum: "6",
                num: "17",
                group1User1: "안성만",
                group1User2: "홍수미",
                group1Score: "13",
                group2Score: "25",
                group2Level: "F-K",
                group2User1: "서형민",
                group2User2: "김남옥",
                round: "결승",
            },
        ],
    },
    {
        id: 1,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제2회 딱플 배드민턴대회",
        competitionYear: "2025",
        teamName: "딱플",
        round: "8강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
        description: "aaaa",
    },
    {
        id: 2,
        name: "홍길동/김철수",
        category: "남복",
        level: "30A",
        competitionName: "제20회 원주시 치악배 오픈 배드민턴대회",
        competitionYear: "2025",
        teamName: "로켓단",
        round: "16강",
        ranking: "3위",
        region: "아산",
        source: "페이스콕",
    },
    {
        id: 3,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제2회 딱플 배드민턴대회",
        competitionYear: "2025",
        teamName: "딱플",
        round: "8강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 4,
        name: "홍길동/김철수",
        category: "남복",
        level: "30A",
        competitionName: "제20회 원주시 치악배 오픈 배드민턴대회",
        competitionYear: "2025",
        teamName: "로켓단",
        round: "16강",
        ranking: "3위",
        region: "아산",
        source: "페이스콕",
    },
    {
        id: 5,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제2회 딱플 배드민턴대회",
        competitionYear: "2024",
        teamName: "딱플",
        round: "8강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 6,
        name: "홍길동/김철수",
        category: "남복",
        level: "30A",
        competitionName: "제20회 원주시 치악배 오픈 배드민턴대회",
        competitionYear: "2024",
        teamName: "로켓단",
        round: "16강",
        ranking: "3위",
        region: "아산",
        source: "페이스콕",
    },
    {
        id: 7,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제13회 무주반딧불 오픈 배드민턴대회",
        competitionYear: "2024",
        teamName: "팀아워",
        round: "4강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 8,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제13회 무주반딧불 오픈 배드민턴대회",
        competitionYear: "2024",
        teamName: "팀아워",
        round: "4강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 9,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제13회 무주반딧불 오픈 배드민턴대회",
        competitionYear: "2024",
        teamName: "팀아워",
        round: "4강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 10,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제13회 무주반딧불 오픈 배드민턴대회",
        competitionYear: "2024",
        teamName: "팀아워",
        round: "4강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 11,
        name: "홍길동/김철수",
        category: "남복",
        level: "30A",
        competitionName: "제20회 원주시 치악배 오픈 배드민턴대회",
        competitionYear: "2024",
        teamName: "로켓단",
        round: "16강",
        ranking: "3위",
        region: "아산",
        source: "페이스콕",
    },
    {
        id: 12,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제13회 무주반딧불 오픈 배드민턴대회",
        competitionYear: "2024",
        teamName: "팀아워",
        round: "4강",
        ranking: "2위",
        score: "25대20",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 13,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30A",
        competitionName: "제2회 딱플 배드민턴대회",
        competitionYear: "2024",
        teamName: "딱플",
        round: "8강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 11,
        name: "홍길동/김철수",
        category: "남복",
        level: "30A",
        competitionName: "제20회 원주시 치악배 오픈 배드민턴대회",
        competitionYear: "2023",
        teamName: "로켓단",
        round: "16강",
        ranking: "3위",
        region: "아산",
        source: "페이스콕",
    },
    {
        id: 12,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30B",
        competitionName: "제13회 무주반딧불 오픈 배드민턴대회",
        competitionYear: "2023",
        teamName: "팀아워",
        round: "4강",
        ranking: "2위",
        score: "25대20",
        region: "천안",
        source: "페이스콕",
    },
    {
        id: 13,
        name: "홍길동/김영희",
        category: "혼복",
        level: "30B",
        competitionName: "제2회 딱플 배드민턴대회",
        competitionYear: "2023",
        teamName: "딱플",
        round: "8강",
        ranking: "2위",
        region: "천안",
        source: "페이스콕",
    },
];

export const tabBarItems = [
    {
        id: 0,
        text: "전체",
    },
    {
        id: 1,
        text: "예정",
    },
    {
        id: 2,
        text: "진행",
    },
    {
        id: 3,
        text: "완료",
    },
];
